### ISSUE TITLE
Bug: Kerberos authentication terminates the main server process

### ISSUE THREAD

**Issue by jholladay10** [auth0/ad-ldap-connector#164]
If the kerberos strategy does not retrieve a record when it queries LDAP the server process crashes with no message.

**Comment by jholladay10** [comment]
It turns out this is not exactly true.  Using kerberos authentication is causing the auth0 tenant to drop the websocket without closing it, which in turn brings down the server process.  The behavior is odd when the kerberos LDAP query retrieves no results, but I don't think it's causing the server process to come down.

**Comment by jfromaniello** [comment]
Thank you for reporting this problem and for the very detailed explanation you sent to my colleagues. It helped me to reproduce and troubleshoot the issue.

It seems is a problem in node.js, this or a similar one:
https://github.com/nodejs/node/issues/21281

I was able to fix it by just upgrading the node.js version to `v8.16.0`.

I have published a new version `v4.2.6` with the change.

Thanks again!

**Comment by jholladay10** [comment]
Hi, Jose.

Unfortunately, this issue is still not fixed.  The issue that was fixed was secondary.  Auth0 is still terminating the websocket connection on a successful authenticaiton request.  The secondary issue that was fixed was only reachable by first disabling the ws-validator component.  With the ws-validator component enabled, the issue you addressed does not occur because it doesn't have a chance to.  Also, it looks like the secondary issue was fixed by something on the Auth0 side as it also no longer occurs for node 8.11.1.

I'd like to keep this open until Auth0 stops terminating the websocket on a successful kerberos authentication.

Jason

**Comment by jfromaniello** [comment]
yes, I get different results than you and I am still investigating. 

First of all the websocket connection get dropped because of this error:

```Error: 4368704960:error:0607A082:digital envelope routines:EVP_CIPHER_CTX_set_key_length:invalid key length:../deps/openssl/openssl/crypto/evp/evp_enc.c:595:```

I figure this out by inserting in `/node_modules/ws/lib/WebSocket.js` line 937 this line of code :

```
console.dir(err);
```

I can reproduce this with `8.11.0` and `8.15.0`, sometimes it doesn't fail immediately but after a few attempts. However, I can't reproduce it with 8.16.

**Comment by jholladay10** [comment]
I will add this line and see what happens for me.

**Comment by jholladay10** [comment]
At line 936 in that module I have this:

function cleanupWebsocketResources(error)

did you mean console.dir(error)? or do we have different versions of this module somehow?  I can't do a clean npm install on this because various builds fail.  So I copied node_modules from a 4.2.3 install.  My ws version is 1.1.5.

**Comment by jfromaniello** [comment]
yes! sorry `console.dir(error)`

**Comment by jholladay10** [comment]
Ok I made the change and tested anyway :)

I did NOT get the disconnect on the first request.  However, I did get the disconnect on the second one:

[2019-06-27 16:56:10] auth0: Agent accepted.
[2019-06-27 16:56:12] latency test took avg: 423.57 ms, max: 1542.46 ms, min: 268.39 ms
::1 - - [27/Jun/2019:16:56:41 +0000] "GET /wsfed?prompt=consent&wprompt=consent&wctx=W2pSDAPyNW3sMZnttLRDzyhu8QDgcAAT&wtrealm=urn%3Aauth0%3Adev-wybf4mq5&wa=wsignin1.0&wreply=https%3A%2F%2Fdev-wybf4mq5.auth0.com%2Flogin%2Fcallback HTTP/1.1" 200 16667 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36"
::1 - - [27/Jun/2019:16:58:29 +0000] "GET /wsfed?prompt=consent&wprompt=consent&wctx=r-J8h9JTbMivd8nPkjUc44En7JpbNAEp&wtrealm=urn%3Aauth0%3Adev-wybf4mq5&wa=wsignin1.0&wreply=https%3A%2F%2Fdev-wybf4mq5.auth0.com%2Flogin%2Fcallback HTTP/1.1" 200 17012 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36"
Error: 0:error:0607A082:digital envelope routines:EVP_CIPHER_CTX_set_key_length:invalid key length:openssl\crypto\evp\evp_enc.c:627:

[2019-06-27 16:58:32] auth0: Connection closed.
[2019-06-27 16:58:33] Exiting with 1

**Comment by jholladay10** [comment]
This was with 8.16.0

**Comment by jholladay10** [comment]
Running the identical test with 8.11.1 I get the error on the first request.

**Comment by jholladay10** [comment]
It might be a timing issue.  I just did this with 8.16.0 again and got it on the first request.

**Comment by jholladay10** [comment]
Did it again and it took 6 requests to get the error:
[2019-06-27 17:02:45] listening on port: 57471
[2019-06-27 17:02:46] jsonwebtoken: expiresInMinutes and expiresInSeconds is deprecated. (C:\Projects\auth0-ad-ldap-connector\ws_validator.js:386:19)
Use "expiresIn" expressed in seconds.
[2019-06-27 17:02:46] auth0: Agent accepted.
[2019-06-27 17:02:48] latency test took avg: 413.58 ms, max: 1613.41 ms, min: 266.78 ms
::1 - - [27/Jun/2019:17:03:28 +0000] "GET /wsfed?prompt=consent&wprompt=consent&wctx=7ggtPjpOWp3HHKACr_Vkhz7GfY779jVg&wtrealm=urn%3Aauth0%3Adev-wybf4mq5&wa=wsignin1.0&wreply=https%3A%2F%2Fdev-wybf4mq5.auth0.com%2Flogin%2Fcallback HTTP/1.1" 200 16667 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36"
::1 - - [27/Jun/2019:17:03:48 +0000] "GET /wsfed?prompt=consent&wprompt=consent&wctx=Zk9xsuuSISeCbVviGDEo_260dTs2mAz2&wtrealm=urn%3Aauth0%3Adev-wybf4mq5&wa=wsignin1.0&wreply=https%3A%2F%2Fdev-wybf4mq5.auth0.com%2Flogin%2Fcallback HTTP/1.1" 200 17012 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36"
::1 - - [27/Jun/2019:17:04:08 +0000] "GET /wsfed?prompt=consent&wprompt=consent&wctx=ycofpZn2-GDIFqdNJZ5rrOBlyD9IjR03&wtrealm=urn%3Aauth0%3Adev-wybf4mq5&wa=wsignin1.0&wreply=https%3A%2F%2Fdev-wybf4mq5.auth0.com%2Flogin%2Fcallback HTTP/1.1" 200 17012 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36"
::1 - - [27/Jun/2019:17:04:28 +0000] "GET /wsfed?prompt=consent&wprompt=consent&wctx=b4gsSjv_IwWwo_1MioVhD7PjKNP-gO6T&wtrealm=urn%3Aauth0%3Adev-wybf4mq5&wa=wsignin1.0&wreply=https%3A%2F%2Fdev-wybf4mq5.auth0.com%2Flogin%2Fcallback HTTP/1.1" 200 17012 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36"
::1 - - [27/Jun/2019:17:04:50 +0000] "GET /wsfed?prompt=consent&wprompt=consent&wctx=ikDjmQdzQnXtlw97n4HR8QS7OOJUcc5H&wtrealm=urn%3Aauth0%3Adev-wybf4mq5&wa=wsignin1.0&wreply=https%3A%2F%2Fdev-wybf4mq5.auth0.com%2Flogin%2Fcallback HTTP/1.1" 200 17012 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36"
Error: 0:error:0607A082:digital envelope routines:EVP_CIPHER_CTX_set_key_length:invalid key length:openssl\crypto\evp\evp_enc.c:627:

[2019-06-27 17:04:53] auth0: Connection closed.
[2019-06-27 17:04:54] Exiting with 1

**Comment by jfromaniello** [comment]
This is very useful to me, thank you very much for helping me to figure it. 

I think as you mention before the problem is still in the 8.x as the fix I linked before doesn't seem to be applied to the 8 branch.

**Comment by jholladay10** [comment]
Glad to help.  I'm going to change that dir to trace and test more on 8.11.1 and see what happens.

**Comment by jholladay10** [comment]
Not very helpful.  However, I had to submit 4 requests on 8.11.1 to get this, so I don't think there's a meaningful difference between the versions with regard to this issue.

[2019-06-27 17:11:27] Trace: Error: 0:error:0607A082:digital envelope routines:EVP_CIPHER_CTX_set_key_length:invalid key length:openssl\crypto\evp\evp_enc.c:595:

    at WebSocket.cleanupWebsocketResources (C:\Projects\auth0-ad-ldap-connector\node_modules\ws\lib\WebSocket.js:938:13)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at TLSSocket._emitTLSError (_tls_wrap.js:598:10)
    at TLSWrap.ssl.onerror (_tls_wrap.js:492:12)
[2019-06-27 17:11:27] auth0: Connection closed.
[2019-06-27 17:11:27] Exiting with 1

**Comment by jfromaniello** [comment]
yes, I got the error with node 8.16 now as well. I am going to try an update to node 10

**Comment by jholladay10** [comment]
Here's some hilarious info.  I wrapped these crypto functions: createCipher, createCipheriv, createDecipher, createDeciveriv.  I also moved into a conference room with a crappy slow wireless connection.  I can see the deciphers being created.  I was unable to get it to fail for 10 requests.  Then while I was typing this comment it failed in a different location where there's no error reporting.

[2019-06-27 18:02:20] jsonwebtoken: expiresInMinutes and expiresInSeconds is deprecated. (C:\Projects\auth0-ad-ldap-connector\ws_validator.js:386:19)
Use "expiresIn" expressed in seconds.
[2019-06-27 18:02:20] auth0: Agent accepted.
[2019-06-27 18:02:23] latency test took avg: 595.84 ms, max: 2306.19 ms, min: 341.6 ms
::1 - - [27/Jun/2019:18:02:37 +0000] "GET /wsfed?prompt=consent&wprompt=consent&wctx=CmO7farxuYYsZ_BdZlnWDuQjyCzrWuI7&wtrealm=urn%3Aauth0%3Adev-wybf4mq5&wa=wsignin1.0&wreply=https%3A%2F%2Fdev-wybf4mq5.auth0.com%2Flogin%2Fcallback HTTP/1.1" 200 16667 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36"
::1 - - [27/Jun/2019:18:03:03 +0000] "GET /wsfed?prompt=consent&wprompt=consent&wctx=LjBQ-VkvgwjTvdhN9gVcd2zMVUEbRVOv&wtrealm=urn%3Aauth0%3Adev-wybf4mq5&wa=wsignin1.0&wreply=https%3A%2F%2Fdev-wybf4mq5.auth0.com%2Flogin%2Fcallback HTTP/1.1" 200 17012 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36"
::1 - - [27/Jun/2019:18:03:22 +0000] "GET /wsfed?prompt=consent&wprompt=consent&wctx=kJAbDc6-rdeuTBZNXSxGYq9W8JSg4PkI&wtrealm=urn%3Aauth0%3Adev-wybf4mq5&wa=wsignin1.0&wreply=https%3A%2F%2Fdev-wybf4mq5.auth0.com%2Flogin%2Fcallback HTTP/1.1" 200 17012 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36"
::1 - - [27/Jun/2019:18:03:42 +0000] "GET /wsfed?prompt=consent&wprompt=consent&wctx=JvkzC5Xh9tSnVRn7CJZVcVBs3VqXb2EV&wtrealm=urn%3Aauth0%3Adev-wybf4mq5&wa=wsignin1.0&wreply=https%3A%2F%2Fdev-wybf4mq5.auth0.com%2Flogin%2Fcallback HTTP/1.1" 200 17012 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36"
::1 - - [27/Jun/2019:18:04:04 +0000] "GET /wsfed?prompt=consent&wprompt=consent&wctx=jDIsvTVnmy13b0ck89Xu4UoFm_g_8jjB&wtrealm=urn%3Aauth0%3Adev-wybf4mq5&wa=wsignin1.0&wreply=https%3A%2F%2Fdev-wybf4mq5.auth0.com%2Flogin%2Fcallback HTTP/1.1" 200 17012 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36"
::1 - - [27/Jun/2019:18:04:23 +0000] "GET /wsfed?prompt=consent&wprompt=consent&wctx=VIm0fVE4nwPHK4nkO3BOCOYFvnW4rtv_&wtrealm=urn%3Aauth0%3Adev-wybf4mq5&wa=wsignin1.0&wreply=https%3A%2F%2Fdev-wybf4mq5.auth0.com%2Flogin%2Fcallback HTTP/1.1" 200 17012 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36"
::1 - - [27/Jun/2019:18:04:41 +0000] "GET /wsfed?prompt=consent&wprompt=consent&wctx=gkz2khaHSBDUabVpQKSntlL3tsS-oRQE&wtrealm=urn%3Aauth0%3Adev-wybf4mq5&wa=wsignin1.0&wreply=https%3A%2F%2Fdev-wybf4mq5.auth0.com%2Flogin%2Fcallback HTTP/1.1" 200 17012 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36"
::1 - - [27/Jun/2019:18:04:59 +0000] "GET /wsfed?prompt=consent&wprompt=consent&wctx=TULMNp7ootEu_Iq7SN7VNgK5qFR_MEw7&wtrealm=urn%3Aauth0%3Adev-wybf4mq5&wa=wsignin1.0&wreply=https%3A%2F%2Fdev-wybf4mq5.auth0.com%2Flogin%2Fcallback HTTP/1.1" 200 17012 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36"
::1 - - [27/Jun/2019:18:05:19 +0000] "GET /wsfed?prompt=consent&wprompt=consent&wctx=717ZeDIq7dpVUf2OdjcQ7_QIEDyr2Fkn&wtrealm=urn%3Aauth0%3Adev-wybf4mq5&wa=wsignin1.0&wreply=https%3A%2F%2Fdev-wybf4mq5.auth0.com%2Flogin%2Fcallback HTTP/1.1" 200 17012 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36"
::1 - - [27/Jun/2019:18:06:22 +0000] "GET /wsfed?prompt=consent&wprompt=consent&wctx=nPqas83XX9qAh3Xrx3RHtpxcxV-KHtKt&wtrealm=urn%3Aauth0%3Adev-wybf4mq5&wa=wsignin1.0&wreply=https%3A%2F%2Fdev-wybf4mq5.auth0.com%2Flogin%2Fcallback HTTP/1.1" 200 17012 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36"
[2019-06-27 18:07:53] auth0: Connection closed.
[2019-06-27 18:07:54] Exiting with 1

**Comment by jholladay10** [comment]
As far as I can tell, this issue was actually addressed in node 11.

**Comment by jholladay10** [comment]
Here's another odd data point.  The result of wrapping the create functions shows that the decipher object is being created twice from the same place during the initialization of the ws_validator.js module.  I didn't think that 'require' worked this way...

***** FIRST TIME *****
    at Object.crypto.createDecipher (C:\Projects\auth0-ad-ldap-connector\fixCryptoSign.js:43:13)
    at Object.exports.decrypt (C:\Projects\auth0-ad-ldap-connector\lib\crypto.js:15:25)
    at initializeConnection (C:\Projects\auth0-ad-ldap-connector\lib\ldap.js:83:75)
    at Object.get [as binder] (C:\Projects\auth0-ad-ldap-connector\lib\ldap.js:113:24)
    at new module.exports (C:\Projects\auth0-ad-ldap-connector\lib\users.js:51:29)
    at Object.<anonymous> (C:\Projects\auth0-ad-ldap-connector\ws_validator.js:9:13)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at C:\Projects\auth0-ad-ldap-connector\server.js:67:15
    at C:\Projects\auth0-ad-ldap-connector\connector-setup\index.js:223:5
    at C:\Projects\auth0-ad-ldap-connector\node_modules\async\lib\async.js:232:13
    at C:\Projects\auth0-ad-ldap-connector\node_modules\async\lib\async.js:142:25
    at C:\Projects\auth0-ad-ldap-connector\node_modules\async\lib\async.js:229:17
    at C:\Projects\auth0-ad-ldap-connector\node_modules\async\lib\async.js:556:34
    at C:\Projects\auth0-ad-ldap-connector\node_modules\nconf\lib\nconf\provider.js:492:34
    at C:\Projects\auth0-ad-ldap-connector\node_modules\nconf\node_modules\async\lib\async.js:206:13
    at C:\Projects\auth0-ad-ldap-connector\node_modules\nconf\node_modules\async\lib\async.js:116:25
    at C:\Projects\auth0-ad-ldap-connector\node_modules\nconf\node_modules\async\lib\async.js:203:17
    at saveStore (C:\Projects\auth0-ad-ldap-connector\node_modules\nconf\lib\nconf\provider.js:479:5)
    at C:\Projects\auth0-ad-ldap-connector\node_modules\nconf\node_modules\async\lib\async.js:201:13
    at iterate (C:\Projects\auth0-ad-ldap-connector\node_modules\nconf\node_modules\async\lib\async.js:108:13)
    at C:\Projects\auth0-ad-ldap-connector\node_modules\nconf\node_modules\async\lib\async.js:119:25
    at C:\Projects\auth0-ad-ldap-connector\node_modules\nconf\node_modules\async\lib\async.js:203:17
    at C:\Projects\auth0-ad-ldap-connector\node_modules\nconf\lib\nconf\provider.js:472:9
    at C:\Projects\auth0-ad-ldap-connector\node_modules\nconf\lib\nconf\stores\file.js:57:34
    at FSReqWrap.oncomplete (fs.js:135:15)

***** SECOND TIME *****
    at Object.crypto.createDecipher (C:\Projects\auth0-ad-ldap-connector\fixCryptoSign.js:43:13)
    at Object.exports.decrypt (C:\Projects\auth0-ad-ldap-connector\lib\crypto.js:15:25)
    at initializeConnection (C:\Projects\auth0-ad-ldap-connector\lib\ldap.js:83:75)
    at Object.get [as client] (C:\Projects\auth0-ad-ldap-connector\lib\ldap.js:104:24)
    at new module.exports (C:\Projects\auth0-ad-ldap-connector\lib\users.js:55:31)
    at Object.<anonymous> (C:\Projects\auth0-ad-ldap-connector\ws_validator.js:9:13)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at C:\Projects\auth0-ad-ldap-connector\server.js:67:15
    at C:\Projects\auth0-ad-ldap-connector\connector-setup\index.js:223:5
    at C:\Projects\auth0-ad-ldap-connector\node_modules\async\lib\async.js:232:13
    at C:\Projects\auth0-ad-ldap-connector\node_modules\async\lib\async.js:142:25
    at C:\Projects\auth0-ad-ldap-connector\node_modules\async\lib\async.js:229:17
    at C:\Projects\auth0-ad-ldap-connector\node_modules\async\lib\async.js:556:34
    at C:\Projects\auth0-ad-ldap-connector\node_modules\nconf\lib\nconf\provider.js:492:34
    at C:\Projects\auth0-ad-ldap-connector\node_modules\nconf\node_modules\async\lib\async.js:206:13
    at C:\Projects\auth0-ad-ldap-connector\node_modules\nconf\node_modules\async\lib\async.js:116:25
    at C:\Projects\auth0-ad-ldap-connector\node_modules\nconf\node_modules\async\lib\async.js:203:17
    at saveStore (C:\Projects\auth0-ad-ldap-connector\node_modules\nconf\lib\nconf\provider.js:479:5)
    at C:\Projects\auth0-ad-ldap-connector\node_modules\nconf\node_modules\async\lib\async.js:201:13
    at iterate (C:\Projects\auth0-ad-ldap-connector\node_modules\nconf\node_modules\async\lib\async.js:108:13)
    at C:\Projects\auth0-ad-ldap-connector\node_modules\nconf\node_modules\async\lib\async.js:119:25
    at C:\Projects\auth0-ad-ldap-connector\node_modules\nconf\node_modules\async\lib\async.js:203:17
    at C:\Projects\auth0-ad-ldap-connector\node_modules\nconf\lib\nconf\provider.js:472:9
    at C:\Projects\auth0-ad-ldap-connector\node_modules\nconf\lib\nconf\stores\file.js:57:34
    at FSReqWrap.oncomplete (fs.js:135:15)

**Comment by jholladay10** [comment]
Heading down a "hail mary" rabbit hole.  I notice that users is calling ldap to create a connection using tls options that are initialized to null.  I don't have my ldap set up as ldaps, so there are no tls options.  I'm thinking that shoving a null tls options through the downstream stuff could cause something to try to set the key length to 0 which would be invalid and go unreported and cause downstream errors.  I'm changing the way the options object is built so that the tlsOptions are absent from the object rather than being explicitly set to null.  We'll see if that has any effect.

**Comment by jholladay10** [comment]
Not failing so far.  I changed line 10 of lib/ldap.js:

function createConnection () {
  var opts = {url:nconf.get("LDAP_URL")};
  if (opts.url.toLowerCase().substr(0, 5) === 'ldaps') {
    opts.tlsOptions = { ca: https.globalAgent.options.ca };
    if (nconf.get('SSL_ENABLE_EMPTY_SUBJECT')) {
      // When enabled use the connector own verification function that fixes Node.js issue described in https://github.com/nodejs/node/issues/11771 for details
      opts.tlsOptions.checkServerIdentity= tls.checkServerIdentity;
    }
  }
  return ldap.createClient(opts);
}

**Comment by jholladay10** [comment]
...still not failing...

**Comment by jholladay10** [comment]
...I think that fixed it.

**Comment by jfromaniello** [comment]
I've been also testing in node v10.16 for an hour and it doesn't fail, I think it was introduced to node 10 since 10.7:

> crypto: handle OpenSSL error queue in CipherBase (Tobias Nießen)

https://github.com/nodejs/node/pull/21851

**Comment by jholladay10** [comment]
Crap. Broke. Maybe there's more than one source for this problem.  Or maybe I didn't get it.

::1 - - [27/Jun/2019:19:06:02 +0000] "GET /wsfed?prompt=consent&wprompt=consent&wctx=Ah-2HIMye9deKCqYQ3NPE4ERS87uKmkc&wtrealm=urn%3Aauth0%3Adev-wybf4mq5&wa=wsignin1.0&wreply=https%3A%2F%2Fdev-wybf4mq5.auth0.com%2Flogin%2Fcallback HTTP/1.1" 200 17012 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36"
[2019-06-27 19:08:55] auth0: Connection closed.
[2019-06-27 19:08:56] Exiting with 1

**Comment by jholladay10** [comment]
17 requests, ran for 14 minutes. Died while I was getting a snack.

**Comment by jholladay10** [comment]
10.7: yes, i see.  I'm not a git expert.  I wish I knew how you found that.

**Comment by jfromaniello** [comment]
I tried reverting to 8 and applied your patch in `createConnection`, after few attempts I got the same error:

```
[2019-06-27 19:17:30] Error: 4449641920:error:0607A082:digital envelope routines:EVP_CIPHER_CTX_set_key_length:invalid key length:../deps/openssl/openssl/crypto/evp/evp_enc.c:627:

[2019-06-27 19:17:30] auth0: Connection closed.
```

**Comment by jholladay10** [comment]
Anecdotal observation?  When my machine has a slower network connection it seems to work better.

**Comment by jfromaniello** [comment]
I am releasing a new major version `v5.0.0`. This version should address the issue with the following changes:

- upgrade to node 10
- reconnect if the WS connection drops instead of crashing the process

Please let me know if this works for you, I appreciate deeply your help so far! thank you

**Comment by jholladay10** [comment]
***** NOTE: I did a clean install on 5.0 and it did not install a certs folder.  I'm going to copy the certs over from a previous install.

**Comment by jholladay10** [comment]
07:16:56 - error: × Connection to LDAP failed.
07:16:56 - error:   > Error: error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt

Here is how I installed:
1. Downloaded from "setup instructions" for my connection
2. Exported config from 4.x installation
3. Installed fresh into new directory
4. Imported config into 5.0.  It stopped the services and did not restart the admin service.
5. Started admin service
6. Ran troubleshooter
7. Got warning for missing certs
8. Copied certs directory from old installation
9. Ran troubleshooter
10. Got this error

**Comment by jfromaniello** [comment]
in addition to the certs you also need the config.json file. 
This error usually happens when your ldap password was encrypted using another certificate, you can also stop the service then remove `LDAP_BIND_CREDENTIALS` from `config.json` and add `LDAP_BIND_PASSWORD` in clear text, the next time you start the service the `LDAP_BIND_PASSWORD` will be encrypted into `LDAP_BIND_CREDENTIALS`..

**Comment by jholladay10** [comment]
I imported my configuration from what was exported from my 4.2.x install so that I would also get my profile mapper.  I also copied the certs directory from my 4.2.x file.  I will fiddle around with it.  I guess I expected the export/import thing to work.

I re-copied the certs and entered my personal LDAP credentials.  That got past the LDAP error.  Maybe the Admin troubleshooter is not self-sufficient and also requires the LDAP service to be running in order to really work?

I am now getting a restart storm with this failure in my log:

2019-06-28T14:38:41.321Z - debug: [2019-06-28 14:38:41] Reading CA certificates from Windows Store
2019-06-28T14:38:41.561Z - debug: [2019-06-28 14:38:41] Adding 54 certificates
2019-06-28T14:38:41.563Z - debug: [2019-06-28 14:38:41] Loading settings from ticket: https://dev-wybf4mq5.auth0.com/p/ad/Qa36RyEn/info
2019-06-28T14:38:42.031Z - debug: [2019-06-28 14:38:42] Local settings updated.
2019-06-28T14:38:42.116Z - debug: [2019-06-28 14:38:42] Certificates already exist, skipping certificate generation.
2019-06-28T14:38:42.122Z - debug: [2019-06-28 14:38:42] Configuring connection PFIAD.
2019-06-28T14:38:42.123Z - debug: [2019-06-28 14:38:42]  > Posting certificates and signInEndpoint: http://DEV-APP02:51873/wsfed
2019-06-28T14:38:42.388Z - debug: [2019-06-28 14:38:42] Connection PFIAD configured.
2019-06-28T14:38:42.390Z - debug: [2019-06-28 14:38:42] Connector setup complete.
2019-06-28T14:38:42.667Z - error: uncaughtException: Cannot find module 'leveldown' date=Fri Jun 28 2019 10:38:42 GMT-0400 (Eastern Daylight Time), pid=6824, uid=null, gid=null, cwd=C:\Auth0\AD LDAP Connector 5.0, execPath=C:\Auth0\AD LDAP Connector 5.0\node.exe, version=v10.16.0, argv=[C:\Auth0\AD LDAP Connector 5.0\node.exe, C:\Auth0\AD LDAP Connector 5.0\server.js], rss=45019136, heapTotal=34738176, heapUsed=19214952, external=633412, loadavg=[0, 0, 0], uptime=1219654, trace=[column=15, file=internal/modules/cjs/loader.js, function=Module._resolveFilename, line=636, method=_resolveFilename, native=false, column=25, file=internal/modules/cjs/loader.js, function=Module._load, line=562, method=_load, native=false, column=17, file=internal/modules/cjs/loader.js, function=Module.require, line=690, method=require, native=false, column=18, file=internal/modules/cjs/helpers.js, function=require, line=25, method=null, native=false, column=17, file=C:\Auth0\AD LDAP Connector 5.0\lib\cache.js, function=null, line=7, method=null, native=false, column=30, file=internal/modules/cjs/loader.js, function=Module._compile, line=776, method=_compile, native=false, column=10, file=internal/modules/cjs/loader.js, function=Module._extensions..js, line=787, method=.js, native=false, column=32, file=internal/modules/cjs/loader.js, function=Module.load, line=653, method=load, native=false, column=12, file=internal/modules/cjs/loader.js, function=tryModuleLoad, line=593, method=null, native=false, column=3, file=internal/modules/cjs/loader.js, function=Module._load, line=585, method=_load, native=false], stack=[Error: Cannot find module 'leveldown',     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15),     at Function.Module._load (internal/modules/cjs/loader.js:562:25),     at Module.require (internal/modules/cjs/loader.js:690:17),     at require (internal/modules/cjs/helpers.js:25:18),     at Object.<anonymous> (C:\Auth0\AD LDAP Connector 5.0\lib\cache.js:7:17),     at Module._compile (internal/modules/cjs/loader.js:776:30),     at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10),     at Module.load (internal/modules/cjs/loader.js:653:32),     at tryModuleLoad (internal/modules/cjs/loader.js:593:12),     at Function.Module._load (internal/modules/cjs/loader.js:585:3)]
2019-06-28T14:38:42.668Z - error: [2019-06-28 14:38:42] Error: Cannot find module 'leveldown'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\Auth0\AD LDAP Connector 5.0\lib\cache.js:7:17)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

**Comment by jholladay10** [comment]
I will try copying the leveldown node module from my previous install to get past this.

**Comment by jholladay10** [comment]
2019-06-28T14:48:07.713Z - error: [2019-06-28 14:48:07] Error: The module '\\?\C:\Auth0\AD LDAP Connector 5.0\node_modules\leveldown\build\Release\leveldown.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 57. This version of Node.js requires
NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:805:18)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at bindings (C:\Auth0\AD LDAP Connector 5.0\node_modules\leveldown\node_modules\bindings\bindings.js:84:48)
    at Object.<anonymous> (C:\Auth0\AD LDAP Connector 5.0\node_modules\leveldown\leveldown.js:4:46)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)

I will try npm install.

**Comment by jholladay10** [comment]
I don't have node and npm set up on this machine.  I don't really want to go down that path if I can avoid it.  I'd rather keep this looking more like a server than a dev box.  I won't be able to try this on my workstation for a couple more hours.

**Comment by jfromaniello** [comment]
if you installed v5 you need to run with node 10, 
you don't need to install or download node on your own, it comes with the installer and it is within the application directory

**Comment by jfromaniello** [comment]
let me see if I can reproduce your issue

**Comment by jholladay10** [comment]
I exported the 4.x config using the admin console.  I uninstalled 4.x.  I installed 5.x in a new directory, so it was completely clean, and I imported the config.  So I assume I should have everything I need in my 5.x directory.  if npm.exe is a part of that, it's in a subdirectory and I didn't really look for it.

**Comment by jholladay10** [comment]
the certs directory was missing from that clean install as well as node_modules/leveldown.

**Comment by jholladay10** [comment]
maybe the certs directory is populated by the service and the troubleshooter doesn't really work until you run the service once?  I was assuming that the troubleshooter handled everything it would need to do its diagnostics.  It definitely behaved differently before I ran the service than it did after I ran the service.

**Comment by jfromaniello** [comment]
You are right, the `v5.0.0` installer is broken 🤦‍♂ 🤦‍♂ 🤦‍♂ 🤦‍♂ 🤦‍♂ 

I've released a new version v5.0.2.

can you try this out?

**Comment by jholladay10** [comment]
Will do

**Comment by jholladay10** [comment]
Installed and running.  My troubleshooter problem was indeed because I hadn't tried to run the service yet.  If I run the troubleshooter before running the service, there are no certs.  Maybe the troubleshooter could create the certs if they're missing or put up a note that it can't check the certs until the service runs.  Probably nobody but me will hit this.

Anyway, the service is running.  This is what's in the log:
2019-06-28T17:35:49.669Z - debug: [2019-06-28 17:35:49] Reading CA certificates from Windows Store
2019-06-28T17:35:49.774Z - debug: [2019-06-28 17:35:49] Adding 54 certificates
2019-06-28T17:35:49.775Z - debug: [2019-06-28 17:35:49] Loading settings from ticket: https://dev-wybf4mq5.auth0.com/p/ad/Qa36RyEn/info
2019-06-28T17:35:50.172Z - debug: [2019-06-28 17:35:50] Local settings updated.
2019-06-28T17:35:50.180Z - debug: [2019-06-28 17:35:50] Generating a self-signed certificate.
2019-06-28T17:35:54.092Z - debug: [2019-06-28 17:35:54] Certificate generated.

2019-06-28T17:35:54.097Z - debug: [2019-06-28 17:35:54] Configuring connection PFIAD.
2019-06-28T17:35:54.097Z - debug: [2019-06-28 17:35:54]  > Posting certificates and signInEndpoint: http://DEV-APP02:51873/wsfed

The little stoplight on the dashboard for the connection is red.  I've refreshed it a few times.  Also I'm not seeing the 'auth0:agent accepted' message that I'd come to expect.  I'm about to try a request...

**Comment by jholladay10** [comment]
from the log...
2019-06-28T17:36:54.346Z - debug: [2019-06-28 17:36:54] Unexpected status while configuring connection: 504
2019-06-28T17:36:54.349Z - debug: [2019-06-28 17:36:54] <html>
<head><title>504 Gateway Time-out</title></head>
<body bgcolor="white">
<center><h1>504 Gateway Time-out</h1></center>
</body>
</html>

I also noticed from the server start that it did not say anything was listening on the kerberos port.  The browser is failing with a timeout, probably because of this.

**Comment by jholladay10** [comment]
...also getting the typical failure/restart storm...

**Comment by jfromaniello** [comment]
This is because it generated a new certificate, it wont be able to connect to auth0 if doesn’t use the cert it generated the first time.

**Comment by jholladay10** [comment]
you mean first time like 4.2.x?  are you saying that installing fresh without carrying the old certs forward will fail?  this seems contrary to the cluster installation instructions where you do fresh installs and export/import the configuration.  is it that the certs should be part of the export/import?

Anyway, i'll go copy them from 4.2.x and see what happens.

**Comment by jholladay10** [comment]
looks like it's working

**Comment by jfromaniello** [comment]
😱😱😱 this has been painful, and definitely not the experience we want for our customers. 
Thank you very much for your help and patience.
We have a lot to do in this component.

**Comment by jholladay10** [comment]
lol, yes, painful, definitely.  Good job figuring this one out.  Having been a developer for my entire career, I understand how this happens.  Thanks for sticking with this one.  I have some more requests, but at least it stays running now.

I did some flipping back and forth with service restarts (turned kerberos off, tested with regular credentials a few times, flipped back).  Seems to be doing okay.  I'm going to test with kerberos on and using windows credentials from outside the network.  One thing I noticed while doing that is that on initial startup with kerberos enabled I didn't get the firewall message.  When I flipped kerberos off and flipped it back on and disabled the cache, this showed up in the log:

2019-06-28T18:19:50.538Z - debug: [2019-06-28 18:19:50] ============================
2019-06-28T18:19:50.539Z - debug: [2019-06-28 18:19:50] Result of Adding a Firewall rule with:
2019-06-28T18:19:50.540Z - debug: [2019-06-28 18:19:50] netsh advfirewall firewall add rule name="Auth0ConnectorKerberos" dir=in action=allow program="C:\Auth0\AD LDAP Connector 5.0.2\node_modules\kerberos-server\kerberosproxy.net\KerberosProxy\bin\Debug\KerberosProxy.exe" profile=private enable=yes
2019-06-28T18:19:50.540Z - debug: [2019-06-28 18:19:50] [object Arguments]
2019-06-28T18:19:50.541Z - debug: [2019-06-28 18:19:50] ============================

This was one of the things that was flat broken in 4.2.3 or whatever due to the lodash upgrade.  I wanted to point this behavior out to you in case it has any meaning.  I'd expect this to come up consistently in relation to kerberos I guess, but that doesn't seem to be what it's doing.

Anyway, thanks for your help.
